# this code was auto generated by pfn

class UnmatchedError(Exception):
	pass

class ArgcountError(Exception):
	pass

def __pfn_call(p, args):
	result=None
	broke=False
	for f in p:
		try:
			result=f(*args)
		except (UnmatchedError, ArgcountError):
			continue
		broke=True

		break
	if not broke:
		raise Exception('no matching function')

	return result
def pfn_avg(*args):
	if len(args) < 1:
		raise ArgcountError('too few arguments for function avg')
	vect = args[0]
	return (sum(vect) / len(vect))

arr=[1,2,3]
print(__pfn_call([pfn_avg], [arr]))
